---
- name: Converge
  hosts: all

  pre_tasks:
    - name: "Update apt cache"
      ansible.builtin.apt:
        cache_valid_time: 600
        update_cache: "yes"
      when: "ansible_os_family == 'Debian'"

  tasks:
    - name: "Include organicveggie.github_cli"
      ansible.builtin.include_role:
        name: "organicveggie.github_cli"
